services:
  - name: next-iot-hub
    type: web
    env: node
    region: frankfurt
    plan: starter
    # dockerfilePath: ./Dockerfile
    # dockerContext: ./
    buildCommand: NODE_ENV=development npm ci && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    branch: main
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: TOKEN_ISSUER
        sync: false
