services:
  - name: stadtpuls-api-v3
    type: web
    env: docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    branch: main
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: ISSUER
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: SUPABASE_MAX_ROWS
        sync: false
