services:
  - name: stadtpuls-api
    type: web
    env: docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    branch: main
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: TOKEN_ISSUER
        sync: false
