# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  LOCATION: "packages/next-iot-hub-api"

on:
  push:
    branches: [main]
    paths: &defaultPaths
      - "$LOCATION/src/**"
  pull_request:
    branches: [main]
    paths: *defaultPaths

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm multi install
      - run: cd $LOCATION
      #      - run: npm ci
      - run: pnpm run build --if-present
      - run: pnpm test
