name: Docker Image Builder

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  release:
    types: [published]
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push to hub.docker.com
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ${{ steps.meta.outputs.tags }}
      - name: Log in to the ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to ghcr.io
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker tag ${{ steps.meta.outputs.tags }} ${{ env.REGISTRY }}/${{ steps.meta.outputs.tags }}
          docker push ${{ env.REGISTRY }}/${{ steps.meta.outputs.tags }}
